### ISSUE TITLE
Add CCRepo support

### ISSUE THREAD

**Issue by hyoretsu** [CookieMonsterTeam/CookieMonster#587]
Add this to package.json, then upload it to CCRepo. (W.I.P.) Just log in with Discord and link to package.json with github.io. It's a nice thing to have all mods in the same place.
Keep in mind that the description property in package.json will be the same description on the site, so a line too long will come out just like Darky's Achievement Package.
```json
,
 "ccrepo": {
  "icon": [
   10,
   0
  ],
  "name": "Cookie Monster"
 }
```
[10, 0] is the icon for default CC cookie.

**Comment by DanielNoord** [comment]
This has been done with #590.
However, since I don't have Discord I can't upload it myself. I have asked the Cppkies team to allow another way of authentication.
Leaving this open until that is done or another way of uploading to CCRepo has been found.

**Comment by davidak** [comment]
What is CCRepo btw?

**Comment by hyoretsu** [comment]
> What is CCRepo btw?

A site to group CC mods together, you use that and a Chrome extension, click on Subscribe button and now you're using the mod.

**Comment by DanielNoord** [comment]
@hyoretsu Do you know if it is still being worked on? Or do you know if they are considering [my issue](https://github.com/Cppkies-Team/CppkiesModRepository/issues/1)?

**Comment by hyoretsu** [comment]
> @hyoretsu Do you know if it is still being worked on? Or do you know if they are considering my issue?

Yeah, just saw they didn't post an answer in GitHub but it's planned (from #dashnet-modding in CC's Discord)

> ʐ̈ MANNNNNNN#2006 — 02/25/2021
I would have to rework the whole auth for that, but fine
I guess I just used discord dev portal so often and always saw the Oauth2 tab and I wanted to try it finally, or something
¯\_(ツ)_/¯
I mean, the authentication process itself isn't that different
Since Oauth2 is a standard, it's always (more or less) the same
The main problem is now I have to generate my own tokens, and manage its expiry date, and track where the auth token came from, etc. etc.
It's not the end of the world, by any means, but I have to put in effort

**Comment by tsr488** [comment]
@DanielNoord I have a Discord account. Is that all we need? I would be glad to upload whatever needs uploading, assuming I have permission to do so, if someone can tell me the steps.

**Comment by DanielNoord** [comment]
I have kept an eye on the repository of CCRepo and the commit frequency has slowed down a little.
I am not sure if the project is still actively maintained.

If so, you have permission to do upload Cookie Monster to their "repo"! I am not sure what that process looks like.

**Comment by DanielNoord** [comment]
@hyoretsu Do you know if the project is still being worked on? The activity on GitHub seems to have died down a little.

**Comment by DanielNoord** [comment]
Going to close this as it seems this project never fully took off. The support will remain in `package.json`.

**Comment by TheGLander** [comment]
@DanielNoord Hello, I am the owner of the CCRepo repository! I added GitHub support just now, it's just that CCRepo is supposed to officially launch together with Cppkies 0.3, so I prefer working on them so that both have roughly the same progress, I finished some Cppkies work, so now I was able to do some rapid CCRepo progress!
