### ISSUE TITLE
Add shortcut buttons and/or keyboard shortcuts for common actions

### ISSUE THREAD

**Issue by TakGalaman** [CookieMonsterTeam/CookieMonster#764]
Add keyboard shortcuts or extra clickable buttons (similar to the "pop wrinkler buttons") to do things like "Mute all buildings" "unmute minigame buildings" "open grimoire (or any minigame)" "Cast force the hand of fate"

**Comment by DanielNoord** [comment]
See [Cookie Monster Shortcuts](https://github.com/CookieMonsterTeam/CookieMonsterShortcuts) a new mod I have been working on that can add Shortcuts to the game. Please add any shortcuts you want as issues there and spread the word!
