### ISSUE TITLE
CookieMonster data API / Expose data variables

### ISSUE THREAD

**Issue by ThexXTURBOXx** [CookieMonsterTeam/CookieMonster#771]
Some time ago, I wrote myself a little script which used CookieMonster's `pp` data to determine which buildings to buy automatically. To achieve this, I had access to many different global variables like
```js
CM.Cache.min
CM.Cache.Objects
CM.Cache.Upgrades
//etc.
```
These variables are all gone now, unfortunately. I also already recursively went down the tree of objects in the current game to see if some of these still exist or are accessible, but I can't seem to find them.

Are these variables somehow still accessible somewhere or won't I be able to extract these data anymore in the future?

If, with the current system, they are not available, consider this as a feature request, which would help me and maybe some other users as well :)

**Comment by DanielNoord** [comment]
The mod has indeed been changed to no longer automatically expose such variables.

But this is indeed a nice feature request. I will try to find something to make this more intuitive!

**Comment by ThexXTURBOXx** [comment]
Okay, thank you very much ~(for telling me I am not completely stupid or insane)~! :)

**Comment by DanielNoord** [comment]
Do you have the code for your script in a repository? Might be helpful for me to test if I implemented the functionality correctly.

**Comment by ThexXTURBOXx** [comment]
It was a very long time ago that I wrote that code, so please don't laugh at me for the code quality lol. My code is here:

<details>
  <summary>Auto CC script</summary>

```js
javascript: (
    function() {
	Game.LoadMod('https://cdn.jsdelivr.net/gh/Aktanusa/CookieMonster@dev/CookieMonster.js');
    }());
var autoGoldenCookie = setInterval(function() {
    for (var h in Game.shimmers) {
        if (Game.shimmers[h].type == "golden") {
            Game.shimmers[h].pop();
        }
    }
}, 1000);
var autoRaeindeer = setInterval(function() {
    for (var h in Game.shimmers) {
        if (Game.shimmers[h].type == "reindeer") {
            Game.shimmers[h].pop();
        }
    }
}, 1000);
var autoClicker = setInterval(Game.ClickCookie, 25);
var autoBuyer = setInterval(function() {
    var building = true;
    var pp = 0;
    var name;
    for (var i in CM.Cache.Objects) {
        if (CM.Cache.Objects[i].pp == CM.Cache.min) {
            pp = CM.Cache.Objects[i].pp;
            name = i;
        }
    }

    for (var i in CM.Cache.Upgrades) {
        if (i != "Shimmering veil [off]" && i != "Shimmering veil [on]" && i != "One mind" && i != "Elder Pledge" && i != "Elder Covenant" && i != "Revoke Elder Covenant" && i != "Festive biscuit" && i != "Ghostly biscuit" && i != "Lovesick biscuit" && i != "Fool's biscuit" && i != "Bunny biscuit" && i != "Golden switch [off]" && i != "Golden switch [on]" && i != "Milk selector" && i != "Golden cookie sound selector" && i != "Background selector") {
            if (!(CM.Cache.Upgrades[i].pp <= 0 || CM.Cache.Upgrades[i].pp == Infinity) && CM.Cache.Upgrades[i].pp < CM.Cache.min) {
                if (CM.Cache.Upgrades[i].pp <= pp) {
                    pp = CM.Cache.Upgrades[i].pp;
                    building = false;
                    name = i;
                }
            }
        }
    }

    if (name != undefined) {
        if (building) {
            Game.Objects[name].buy();
        } else {
            Game.Upgrades[name].buy();
        }
    }
}, 25);

var fortuneClicker = setInterval(function() {
    if (Game.TickerEffect && Game.TickerEffect.type == 'fortune') {
        Game.tickerL.click();
    }
}, 3000);
```

</details>

**Comment by DanielNoord** [comment]
Sorry for only getting back on this now.
Looking at your code I think exporting the `Upgrades` and `Buildings` object to the global scope should make your script run again. However, the structure of these objects have changed somewhat since you last wrote your code.

I can certainly export them, but you will probably have to make some slight changes.

Is there any data that you think might be relevant or useful? As I can export them at the same time.

**Comment by ThexXTURBOXx** [comment]
Hi, sorry, I wasn't home until now.

That's no problem. I should refactor stuff in my script anyways :)

Any other data... I think, stuff that has to do with Wrinklers, statistics or something like that might be useful... But I am not sure how many other people may depend on data coming from CookieMonster 🤔

**Comment by ThexXTURBOXx** [comment]
Got my script working again with the new API, thank you very much :)
