### ISSUE TITLE
Buildings and upgrades (almost) never show green or blue

### ISSUE THREAD

**Issue by rixccc** [CookieMonsterTeam/CookieMonster#773]
Buildings and upgrades (almost) never show green or blue

upon loadin

![Screenshot (2)](https://user-images.githubusercontent.com/82873743/115371757-8a425200-a1ca-11eb-9852-d296f3f04d19.png)
[RixBakery (1).txt](https://github.com/Aktanusa/CookieMonster/files/6342317/RixBakery.1.txt)

**Comment by DanielNoord** [comment]
Have you checked the buy 10 column? There might actually be a building there.
Sometimes it is better to buy more of a building to trigger a new achievement. CM shows this by marking the building green in the buy 10 column.

**Comment by rixccc** [comment]
Thanks. It is this

**Comment by DanielNoord** [comment]
I will keep this issue open as a reminder to make this even more explicit in the docs and tooltips

**Comment by TakGalaman** [comment]
Could we have a color that means "Best building to buy on screen" and another color that means "Best building+bulk buy mode overall". Or what about highlighting the "buy 10" button with the "best PP" color if the current bulk buy mode doesn't show a blue/green (best PP color) building?

**Comment by puggan** [comment]
I'd like to see some indicator, if buying 10x has a better PP, then the "x10" is shown in that PP:s color, like:
![2021-05-02 (4)](https://user-images.githubusercontent.com/866668/116807518-da5ad600-ab33-11eb-95fb-4231c1cc5a15.png)
(maybe add some more margin so its not to close to the 1x price)

**Comment by DanielNoord** [comment]
I'm more in favour of @TakGalaman's solution of coloring the "buy 10" button (or finding another way to make it stand out). Adding the (x10) to the button might confuse users, especially newer ones who seem to be struggling the most with this feature and its implementation.
