### ISSUE TITLE
IMPORTANT: Cookie Monster not loading

### ISSUE THREAD

**Issue by DanielNoord** [CookieMonsterTeam/CookieMonster#784]
Because of a change of repository ownership the link to load CookieMonster has been changed.
The new location of the file is
https://cookiemonsterteam.github.io/CookieMonster/dist/CookieMonster.js
This link should work for all methods of loading the mod.

An update to the Readme, wiki entry and a new version of the mod itself will be pushed out tomorrow. In the meantime this should resolve most issues!

**Comment by FayneAldan** [comment]
Can I suggest making a new repo in the original location (under @Aktanusa's account) where `CookieMonster.js` and `CookieMonsterBeta.js` both just contain:
```javascript
Game.LoadMod('https://cookiemonsterteam.github.io/CookieMonster/dist/CookieMonster.js');
```

**Comment by DanielNoord** [comment]
@Aktanusa could do this, but this might create the problem of people opening issues in their repository. They are quite busy so they might not always have the time to direct them here. 
I'm hoping that after this weekend every user will find the new repo! Perhaps @Aktanusa can clone the repo and add a line to the Readme directing to this new location?

**Comment by Aktanusa** [comment]
Sorry just saw this.  Interesting idea.  Um.. I'm sure it will be fine after a few months, right? Haha
