### ISSUE TITLE
Payback Clicks

### ISSUE THREAD

**Issue by puggan** [CookieMonsterTeam/CookieMonster#785]
**Describe the function you'd like to see added to CookieMonster**
Gray upgrades that doesn't increase the CPS, but increase the Cookies per click,
can have a "Paybacks Clicks". `[Payback clicks = ceiling( increased cookies per click / price )]`

**Comment by puggan** [comment]
If I want to test to implement this and make a PR, what branch should I build from? (master, beta, dev)

**Comment by DanielNoord** [comment]
You should build from dev for new functions.
However, I thought we already did this. Do you have a save in which this function does not work?

**Comment by puggan** [comment]
Try my old save from #780
![2021-05-02 (1)](https://user-images.githubusercontent.com/866668/116805892-c5794500-ab29-11eb-9a99-209e9ae1a45a.png)

Same as in my Current game:
![2021-05-02](https://user-images.githubusercontent.com/866668/116805824-3ec46800-ab29-11eb-8cf2-b826b0111e18.png)

Is there an option that I have to check to get an extra row with  "Paybacks Clicks"

**Comment by puggan** [comment]
Think this if:
https://github.com/CookieMonsterTeam/CookieMonster/blob/76c6d584df355d68c1534e0ce893856b7841534e/src/Disp/Tooltips/TypesOfTooltips/Upgrade.js#L33-L38

prevent this part from running:
https://github.com/CookieMonsterTeam/CookieMonster/blob/76c6d584df355d68c1534e0ce893856b7841534e/src/Disp/Tooltips/TypesOfTooltips/Upgrade.js#L49-L53

**Comment by DanielNoord** [comment]
Oh yeah, that's it!
Pushing out a hot fix asap

**Comment by puggan** [comment]
This seams to work: #788

**Comment by DanielNoord** [comment]
Thanks!!
