### ISSUE TITLE
Cookie Monster currently not loading for me

### ISSUE THREAD

**Issue by jeffslutzky** [CookieMonsterTeam/CookieMonster#798]
It usually works for me (including yesterday), but today it's not loading when I click on the bookmark.

Here's my save if that helps:
Mi4wMzF8fDE2MTk4OTc5MTYyNTU7MTU5MTU1Nzk5OTI4NDsxNjE5OTY2MDMxMDc1O0plZmY7YXl0a3R8MDExMTAwMDAwMDAwMDAwMDAxMDAwfDEuMzE0MTkwNjg5Mzc3OTY2NWUrNTI7MS42NzgxNDgzMTgwNjQyMTY0ZSs1MzsxODcxOzM2Njc2OzEuMDM5NjgwODQ4MTQ1OTE4N2UrNTM7MTA5MjE7MTsyMjsyLjcwODEyNDM1OTQ4NTkzM2UrNTc7MDsyOzUzMTk1OzA7LTE7MTMyOzQyOzguODkzNjA4MDgzMzI0NjM1ZSs0OTs3OTsxNDs4OzY3NTQ3ODs0O2Vhc3RlcjswOzA7MTM5Mzg3MTkxNTg2MjY4NTsxMzkxNjg1MDY1Njc0NTkzOzIxODY4NTAxODgwOTI7MDswOzY3OTs2ODA7NjU5OzcxNjs2Nzg7MjU7MTU7MTsxOzM5OzA7MDsyOzM5NzsxNjE5ODk3OTU5NDY5OzA7MDs7NDE7MDsxOzcuMTkzODU3NjM3ODU0NzAzZSs0Njt8ODEwLDE1MzcwLDQuODIzNzIzNDUzNDY0MDQ0ZSs0OSw4LCwwLDgxMDs3OTAsMTE0MCwzLjU4Nzc5MjEwNTEwNTk5ODdlKzQ5LDQsLDEsNzkwOzc2MCwxMTEwLDEuOTYzODA2ODYwNzY2NzU1MmUrNDYsMTAsMTYxOTk2Njc1MTEyMjoyOjE2MTk4OTg4OTU0MDE6MDowOjMxODc6MToyOjE2MTk4OTc5MTYyNzI6IDExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTEgNjo3NDo2OjczOjY6NzQ6Njo4MTo2OjgxOjY6Nzc6Njo1ODo2Ojc1OjY6Njg6Njo4MDo2OjY2OjY6ODk6Njo3MTo2Ojc4OjY6ODc6Njo3OTo2Ojc1OjY6NjU6Njo2OTo2Ojc0OjY6Nzk6Njo3NDo2Ojc0OjY6NzY6Njo2OTo2Ojg4OjY6NTc6Njo4Mjo2OjcxOjY6NjE6Njo4Nzo2OjY2OjY6Njg6Njo2MTo2OjU0OjY6Nzg6LDAsNzYwOzc0MCwxMDkwLDEuNzc3NjkwNTc4ODkyNTUyNmUrNDgsNCwsMSw3NDA7NzIwLDEwNzAsMi4xNTM5MTAxODg2NzMzNTQ0ZSs0Nyw0LCwxLDcyMDs3MTAsMTA2MCw0LjY3MDM4MDAyMTAyNjUzNWUrNDYsNCwwOjA6MTowOjA6IDgxMzo0Oi05NjoxMzM6MDowOjAhMzU5ODoxOjM2OjI3NzowOjA6MCE0NzQ3OjE6MzU6NTQ5OjA6MDowITE5OTQ6NTotNDA6MTY3OjA6MDowITkwNzo0Oi0xNTA6Mjg2OjA6MDowITc1OTU6MDoyMDoyODk6MDowOjAhNDI5NTo0Oi0xMDg6NTcxOjA6MDowITgzMjU6MDoxMjozMzE6MDowOjAhNjcyODo1OjIzOjEyODowOjA6MCExMDg1MzoxOjU6Mzg6MDowOjAhMTE2OTk6MToxMzo0OTM6MDowOjAhMTA2NjI6MjotNDk6ODY0OjA6MDowITEyODE1OjE6MjI6OTI1OjA6MDowITE0ODMzOjE6MTo1MzE6MDowOjAhMTQ3Mzc6NToxMjoyMDM6MDowOjAhMTY3NDQ6MToxMzoxNTI6MDowOjAhIDAsMSw3MTA7NjkwLDEwNDAsMS44ODg3MDYzNjIyMjcwNDQzZSs0Nyw0LDIvMTAvLTEgMiAxNjE5OTY1ODE1NTgyIDEsMSw2OTA7Njg1LDE2MzAsNi4xMzc4NTk5ODcwNTQ5MTNlKzQ2LDEwLDI2LjI4MDMzMjkyMTQ0NDggMyAyNDcwIDEsMCw2ODU7NjUwLDEwMDAsMS42NTE0NDgwMzAzMDMzODU3ZSs0Niw0LCwxLDY1MDs2MzAsOTgwLDguOTQwOTY0NDc3MzU1NTQ5ZSs0Niw0LCwxLDYzMDs2MTAsOTYwLDEuMzEzNjQ2MDE5MjYyODIzNWUrNDksNCwsMSw2MTA7NTkwLDk0MCwzLjA1MjE1MjUzMjk0NzYwMTRlKzQ4LDQsLDEsNTkwOzU3MCw5MjAsMy4wMDY2MjgxMzY4NTQwMjhlKzQ5LDQsLDEsNTcwOzU2MCw5MTAsMS42MjYyNTQ1NDczOTMzMTY0ZSs1MCw0LCwxLDU2MDs1NTAsOTAwLDQuMTE1MzU4NDIyMjgyMjg4ZSs1MCw0LCwxLDU1MDs1MzAsODgwLDIuNTE2MDY4MzI4NDY0MTg5OGUrNTEsNCwsMSw1MzA7NTAwLDg1MCw1Ljk5NjM5MDY4NDYzNTQ5M2UrNTAsMTAsLDEsNTAwOzQ5Niw4NDYsNC42NzY5Njg4MzQ4MzEyNjZlKzUxLDEwLCwxLDQ5Njt8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTAwMTAwMDExMDAxMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMTEwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTAxMDEwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMDAxMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTAwMTExMTExMTExMTExMTExMTExMDAwMDAwMTExMTAwMTExMTExMTExMTExMTExMTExMTAxMDEwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDExMTExMTExfDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDEwMDAwMTAwMDAwMDExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTEwMDExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMDExMTExMTExMDEwMDAwMDB8MCwxOTE4MywxMjM2Niw3LDAsMDsxMywxMDgwMDAsODgzNDYsMiwwLDA7Miw0NTYwLDM1NTIsMC41O3xDb29raWVNb25zdGVyOnsiZmF2b3VyaXRlU2V0dGluZ3MiOltdLCJzZXR0aW5ncyI6eyJCb3RCYXIiOjAsIlRpbWVyQmFyIjoxLCJUaW1lckJhclBvcyI6MCwiQnVpbGRDb2xvciI6MCwiQnVsa0J1aWxkQ29sb3IiOjAsIkNvbG9yUFBCdWxrTW9kZSI6MCwiVXBCYXJDb2xvciI6MCwiVXBncmFkZUJhckZpeGVkUG9zIjowLCJDYWxjV3JpbmsiOjAsIkNQU01vZGUiOjEsIkF2Z0NQU0hpc3QiOjMsIkF2Z0NsaWNrc0hpc3QiOjAsIlRvb2xXYXJuQm9uIjowLCJHQ05vdGlmaWNhdGlvbiI6MCwiR0NGbGFzaCI6MCwiR0NTb3VuZCI6MCwiR0NWb2x1bWUiOjEwMCwiR0NTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzY2LzY2NzE3XzkzMTY1NS1scS5tcDMiLCJGb3J0dW5lTm90aWZpY2F0aW9uIjowLCJGb3J0dW5lRmxhc2giOjAsIkZvcnR1bmVTb3VuZCI6MSwiRm9ydHVuZVZvbHVtZSI6NzAsIkZvcnR1bmVTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzE3NC8xNzQwMjdfMzI0MjQ5NC1scS5tcDMiLCJTZWFOb3RpZmljYXRpb24iOjAsIlNlYUZsYXNoIjowLCJTZWFTb3VuZCI6MCwiU2VhVm9sdW1lIjoxMDAsIlNlYVNvdW5kVVJMIjoiaHR0cHM6Ly93d3cuZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyMS8xMjEwOTlfMjE5MzI2Ni1scS5tcDMiLCJHYXJkRmxhc2giOjAsIkdhcmRTb3VuZCI6MCwiR2FyZFZvbHVtZSI6MTAwLCJHYXJkU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMDMvMTAzMDQ2Xzg2MTcxNC1scS5tcDMiLCJNYWdpY05vdGlmaWNhdGlvbiI6MCwiTWFnaWNGbGFzaCI6MCwiTWFnaWNTb3VuZCI6MCwiTWFnaWNWb2x1bWUiOjEwMCwiTWFnaWNTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzIyMS8yMjE2ODNfMTAxNTI0MC1scS5tcDMiLCJXcmlua2xlck5vdGlmaWNhdGlvbiI6MCwiV3JpbmtsZXJGbGFzaCI6MCwiV3JpbmtsZXJTb3VuZCI6MCwiV3JpbmtsZXJWb2x1bWUiOjEwMCwiV3JpbmtsZXJTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyNC8xMjQxODZfODA0My1scS5tcDMiLCJXcmlua2xlck1heE5vdGlmaWNhdGlvbiI6MCwiV3JpbmtsZXJNYXhGbGFzaCI6MCwiV3JpbmtsZXJNYXhTb3VuZCI6MCwiV3JpbmtsZXJNYXhWb2x1bWUiOjEwMCwiV3JpbmtsZXJNYXhTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzE1Mi8xNTI3NDNfMTU2NjMtbHEubXAzIiwiVGl0bGUiOjEsIlRvb2x0aXBCdWlsZFVwIjowLCJUb29sdGlwQW1vciI6MCwiVG9vbFdhcm5MdWNreSI6MCwiVG9vbFdhcm5MdWNreUZyZW56eSI6MCwiVG9vbFdhcm5Db25qdXJlIjowLCJUb29sV2FybkVkaWZpY2UiOjAsIlRvb2xXYXJuUG9zIjoxLCJUb29sdGlwR3JpbSI6MSwiVG9vbFdyaW5rIjowLCJUb29sdGlwTHVtcCI6MSwiRHJhZ29uQXVyYUluZm8iOjEsIlN0YXRzIjowLCJNaXNzaW5nVXBncmFkZXMiOjAsIlVwU3RhdHMiOjEsIlRpbWVGb3JtYXQiOjAsIkRldGFpbGVkVGltZSI6MSwiR3JpbW9pcmVCYXIiOjEsIlNjYWxlIjowLCJTY2FsZURlY2ltYWxzIjoyLCJTY2FsZVNlcGFyYXRvciI6MSwiU2NhbGVDdXRvZmYiOjk5OTk5OSwiU29ydEJ1aWxkaW5ncyI6MCwiU29ydFVwZ3JhZGVzIjowLCJHQ1RpbWVyIjoxLCJGYXZpY29uIjoxLCJXcmlua2xlckJ1dHRvbnMiOjAsIkhlYWRlciI6eyJCYXJzQ29sb3JzIjoxLCJDYWxjdWxhdGlvbiI6MSwiTm90aWZpY2F0aW9uIjoxLCJOb3RpZmljYXRpb25HQyI6MSwiTm90aWZpY2F0aW9uRkMiOjEsIk5vdGlmaWNhdGlvblNlYSI6MSwiTm90aWZpY2F0aW9uR2FyZCI6MSwiTm90aWZpY2F0aW9uTWFnaSI6MSwiTm90aWZpY2F0aW9uV3JpbmsiOjEsIk5vdGlmaWNhdGlvbldyaW5rTWF4IjoxLCJUb29sdGlwIjoxLCJTdGF0aXN0aWNzIjoxLCJOb3RhdGlvbiI6MSwiTWlzY2VsbGFuZW91cyI6MSwiTHVja3kiOjEsIlNwZWxscyI6MSwiQ2hhaW4iOjEsIlByZXN0aWdlIjoxLCJXcmluayI6MSwiU2VhIjoxLCJNaXNjIjoxLCJOb3RpZmljYXRpb25HZW5lcmFsIjoxLCJHYXJkZW4iOjEsIkluZm9UYWIiOjEsIkZhdm91cml0ZSI6MSwiQ29sb3VycyI6MSwiQmFyc0Rpc3BsYXkiOjF9LCJUb29sdGlwSW5mbyI6MCwiVG9vbFdhcm5Db25qdXJlRnJlbnp5IjowLCJUaW1lckJhck92ZXJsYXkiOjEsIlBQRXhjbHVkZVRvcCI6MCwiUFBTZWNvbmRzTG93ZXJMaW1pdCI6MCwiUFBPbmx5Q29uc2lkZXJCdXlhYmxlIjowLCJHZW5lcmFsU291bmQiOjEsIlRvb2x0aXBCdWlsZFVwZ3JhZGUiOjAsIlRvb2xXYXJuVXNlciI6MCwiVG9vbHRpcFdyaW5rIjowLCJUb29sdGlwUGxvdHMiOjEsIlRvb2x0aXBBc2NlbmRCdXR0b24iOjEsIkhlYXZlbmx5Q2hpcHNUYXJnZXQiOjEsIlNob3dNaXNzZWRHQyI6MSwiQnVsa0J1eUJsb2NrIjowLCJQUERpc3BsYXlUaW1lIjowLCJUb29sdGlwUGFudGhlb24iOjEsIkhpZGVTZWN0aW9uc0J1dHRvbnMiOjAsIlBQUmlnaWRlbE1vZGUiOjAsIkJ1aWxkQ29sb3VyIjowLCJDb2xvdXJCbHVlIjoiIzRiYjhmMCIsIkNvbG91ckdyZWVuIjoiIzAwZmYwMCIsIkNvbG91clllbGxvdyI6IiNmZmZmMDAiLCJDb2xvdXJPcmFuZ2UiOiIjZmY3ZjAwIiwiQ29sb3VyUmVkIjoiI2ZmMDAwMCIsIkNvbG91clB1cnBsZSI6IiNmZjAwZmYiLCJDb2xvdXJHcmF5IjoiI2IzYjNiMyIsIkNvbG91clBpbmsiOiIjZmYxNDkzIiwiQ29sb3VyQnJvd24iOiIjOGI0NTEzIiwiVXBCYXJDb2xvdXIiOjAsIk1pc3NpbmdBY2hpZXZlbWVudHMiOjAsIkNvbG91ckdDRmxhc2giOiIjZmZmZmZmIiwiQ29sb3VyRm9ydHVuZUZsYXNoIjoiI2ZmZmZmZiIsIkNvbG91clNlYUZsYXNoIjoiI2ZmZmZmZiIsIkNvbG91ckdhcmRGbGFzaCI6IiNmZmZmZmYiLCJDb2xvdXJNYWdpY0ZsYXNoIjoiI2ZmZmZmZiIsIkNvbG91cldyaW5rbGVyRmxhc2giOiIjZmZmZmZmIiwiQ29sb3VyV3JpbmtsZXJNYXhGbGFzaCI6IiNmZmZmZmYiLCJGYXZvdXJpdGVTZXR0aW5ncyI6MH0sInZlcnNpb24iOiIyLjAzMS43In07%21END%21

**Comment by DanielNoord** [comment]
We have moved the repository and therefore you need to use a new link to load the mod (see the Readme).
Does it still not work with the new link?

**Comment by jeffslutzky** [comment]
Ah thanks! The new link works.
