### ISSUE TITLE
Cannot load script at all

### ISSUE THREAD

**Issue by AmyLucyRose** [CookieMonsterTeam/CookieMonster#806]
**Describe the bug**
Cookie Monster does not load at all, no matter what. I'm mainly using the bookmarklet method, I have re-pasted the code inside of it, and I have also tried pasting code directly to the javascript console.
Please not that it worked perfectly fine until around last weekend, I am a long time user of the mod (if with most features turned off, preserving most of the vanilla game experience with just some cookie-spending help)

**To Reproduce**
The steps needed to reproduce the behavior:
1. Try to load the mod
2. Nothing happens at all

**Save file**
```
[AmbrosineBakery(1).txt](https://github.com/CookieMonsterTeam/CookieMonster/files/6441614/AmbrosineBakery.1.txt)
```
**Browser**
Firefox 88.0.1 64 bit, running on Windows 10 build 19042.928, using https version of cookie clicker.
I am usually using "disable all third party cookies", but switching that to allowing all cookies does not resolve the issue

**Comment by DanielNoord** [comment]
Could you show the code you have entered into your bookmarklet?

**Comment by AmyLucyRose** [comment]
> 
> 
> Could you show the code you have entered into your bookmarklet?

Bookmarklet code is :
```
javascript: (function () { Game.LoadMod('https://aktanusa.github.io/CookieMonster/CookieMonster.js'); }());
```

**Comment by AmyLucyRose** [comment]
> 
> 
> Could you show the code you have entered into your bookmarklet?

Update : renewing the bookmarklet code fixed the issue ?
I do not understand why as I had already done that twice previously !?

Sorry for the inconvenience caused

**Comment by DanielNoord** [comment]
We have moved the repository, which has also changed the link needed to load the mod.
The new code for the bookmarklet would be:
```javascript
javascript: (function () {
	Game.LoadMod('https://cookiemonsterteam.github.io/CookieMonster/dist/CookieMonster.js');
}());```
That should work!

**Comment by AmyLucyRose** [comment]
> 
> 
> We have moved the repository, which has also changed the link needed to load the mod.
> The new code for the bookmarklet would be:
> 
> ```js
> javascript: (function () {
> 	Game.LoadMod('https://cookiemonsterteam.github.io/CookieMonster/dist/CookieMonster.js');
> }());
> ```
> 
> That should work!

I think that was the issue, I had no idea the move had occured, and there was no in-game notice
Thanks for the help anyway

**Comment by DanielNoord** [comment]
Sadly we could not easily keep the old version running while also moving the repository.
Therefore, it was difficult to give a real notice to users. Glad to hear it works again!
