### ISSUE TITLE
Make it easier to see the season special status you're looking for in the statistics window

### ISSUE THREAD

**Issue by TakGalaman** [CookieMonsterTeam/CookieMonster#821]
In the stats page in the season specials section it lists how many special cookies remain for various seasons, but since it's plaintext it's tough to quickly spot the part I want to know. 

I think increasing the font size of lines relevant to the currently active season, or adding a little icon/emoji to the left corresponding to the season for each line would make spotting the right line easier.
![image](https://user-images.githubusercontent.com/31801070/118533446-b4295e80-b70d-11eb-9080-faf871446ec8.png)

I am aware that hovering on the season switcher gives a VERY nice display of the remaining special cookies/eggs/etc. Showing that for the currently active season in statistics may be the answer. 
![image](https://user-images.githubusercontent.com/31801070/118534182-8ee92000-b70e-11eb-9778-0cd76b6c701a.png)

**Comment by DanielNoord** [comment]
I have implemented a new feature that colours the season entries depending on current season. This should help with the problem you mentioned. See screenshot.

<img width="566" alt="Schermafbeelding 2021-05-30 om 11 48 06" src="https://user-images.githubusercontent.com/13665637/120099639-ea6ad300-c13c-11eb-8746-6638c1b9325f.png">

**Comment by TakGalaman** [comment]
Nice!
