### ISSUE TITLE
Dragon claw and fang show up under missing normal upgrades as Vaulted

### ISSUE THREAD

**Issue by faulk28** [CookieMonsterTeam/CookieMonster#831]
The Dragon claw and Dragon Fang show up under missing normal upgrades on the stats page as Vaulted however there is nothing in the vault in the screenshot. Did they vanish from the game?

**To Reproduce**
Not sure how this occurred. It started early after ascending.

**Screenshots**
See attached
[Faulk28Bakery (96).txt](https://github.com/CookieMonsterTeam/CookieMonster/files/6538509/Faulk28Bakery.96.txt)
![cookies bug screenshot](https://user-images.githubusercontent.com/74863828/119482805-49d27880-bd22-11eb-9258-309ccfcb9282.jpg)

**Save file**
See above

**Browser**
Google Chrome on Windows 10 90.4.4430.212 Official Build 64 bit

**Comment by faulk28** [comment]
Update I think its just a cosmetic glitch. The glitch is they are labeled as "vaulted" when they are now. I kept clicking on the dragon and eventually the missing drops came out.

**Comment by DanielNoord** [comment]
Are you sure you did not vault them previously?
In my own testing they do not show up as vaulted when they are not yet buyable after clicking the dragon. Perhaps you vaulted these upgrades in an earlier run and the game remembers that through ascensions?
