### ISSUE TITLE
Allow sorting by cost till next achievement / include info in statistics page

### ISSUE THREAD

**Issue by TakGalaman** [CookieMonsterTeam/CookieMonster#833]
At my current stage buying buildings alone is not very cost effective, so I pretty much only buy if it means I can jump up to claim another achievement. 

I currently mouse through all the buildings and look at the cost till next achievement on each one to decide if I should buy.

I'd like an option to sort the building list to keep the building with the lowest cost to gain another achievement at the top. Alternatively my purpose would be served by showing the "cost to next achievement" on the bottom infobar so I don't need to mouse over all of them.

**Comment by DanielNoord** [comment]
I don't want to add this information to the bottom bar as I feel that that bar is already quite full.

Personally I think the best (and least intrusive) way to show this data is by adding a section to the statistics page which updates every tick and displays the data for each building. This should be do-able.

**Comment by tsr488** [comment]
Agree that the bottom bar is already full. A section on the statistics page would work, but I like the idea of a new sort option. Added a PR in case we decide this is the way to go.

**Comment by DanielNoord** [comment]
Just had a quick look at #848, seems like a good addition.
Will take a better look tomorrow and probably merge it after. Good chance to also check out your work on the merge-workflow.

Will keep this issue open though as I believe adding this info to the statistics page is also something we should do before the next release.
Considering we already have the calculations that are necessary for this, it should be fairly trivial to add this to the statistics page.

**Comment by DanielNoord** [comment]
Although #848 adds sorting by next achievement, I will keep this issue open to track progress on adding the info on next achievements to the statistics page
