### ISSUE TITLE
Option to completely disregard certain building types

### ISSUE THREAD

**Issue by Nettingman** [CookieMonsterTeam/CookieMonster#843]
I'm keeping my number of wizard towers to 2 for fast Conjure Baked Goods manaregen since the towers won't provide a significant CpS in late game anyway. I was wondering if there could be some setting to completely ignore certain building types (or just wizard tower), even if their PP is better than any other building's.

**Comment by DanielNoord** [comment]
Doesn't the "ignore x top buildings" option fulfil your needs? Or doesn't that cover all your use cases?

**Comment by Nettingman** [comment]
Sorry, I did not realize this feature existed, there are so many options.
I could filter out wizard towers now (although I had to ignore the top 2, because the second best building was 10xWizard towers) :)

Thank you!

**Comment by DanielNoord** [comment]
Glad you found something that worked!
