### ISSUE TITLE
Error after upgrading Krumblor to 1st aura slot

### ISSUE THREAD

**Issue by Rau117** [CookieMonsterTeam/CookieMonster#854]
**Describe the bug**
Calculations don't work after loading the mod, error at Dragon.js line 22

**To Reproduce**
Upgrade Krumblor to 1st aura level

**Screenshots**
(yellow sign before is about Tracking Protection)
![изображение](https://user-images.githubusercontent.com/47086324/121274706-bb3e2980-c8d3-11eb-985c-c4ef54c05635.png)

**Save file**
[RauBakery(1).txt](https://github.com/CookieMonsterTeam/CookieMonster/files/6620379/RauBakery.1.txt)

**Browser**
Cookie Clicker 2.031; https version, Firefox 0.75

**Comment by DanielNoord** [comment]
Sadly Firefox 75.0 is not supported. The functionality of `replaceAll()` was only added in Firefox 77.0, as is shown [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll).

Would you be able to upgrade your browser? Or are there any restrictions that keep you on Firefox 75.0?
