### ISSUE TITLE
"Ignore 1st best" setting for identifying best building applies incorrectly for bulk buy modes

### ISSUE THREAD

**Issue by TakGalaman** [CookieMonsterTeam/CookieMonster#886]
**Describe the bug**
I sold off Wizard towers to change my mana pool, so now my number of wizard towers is "artificially low" and I don't want to consider wizard towers when looking for the most cost-efficient building to buy, so I set cookie monster to ignore the 1st best building. 
In the "buy 1" view of buildings wizard towers are gray, but nothing is highlighted in green/blue.
![image](https://user-images.githubusercontent.com/31801070/124940029-3b3cd980-dfcf-11eb-80d2-ac0a350774aa.png)

In the "buy 10" view wizard towers are blue! I don't like this because it's unsurprising that wizard towers are cost-effective. I'm holding their numbers low. I want to know what building to buy most cost-effectively.
![image](https://user-images.githubusercontent.com/31801070/124940069-455ed800-dfcf-11eb-9086-446b486cb82a.png)

I can "work around" this by setting cookie monster to ignore the first 3 best (wizard towers x1, x10, and x100). It then highlights antimatter condensers as best. (Maybe the reason you gave the option to ignore the 3 best rather than some other number is for PRECISELY THIS PURPOSE/REASON!)

Desired behavior:
When I say "ignore 1st best" I want it to ignore the building as a whole. Whichever building has the best PP should be grayed out on all modes of bulk buy.

**To Reproduce**
The steps needed to reproduce the behavior:
1. Load my save and look at the settings I have. toggle the "ignore 1st/2nd/3rd best" and look at wizard towers in all 3 bulk buy modes

**Save file**
Mi4wMzF8fDE2MjU1OTkzMDcyMDQ7MTYxMDc0ODI4MzQ5NzsxNjI1NzU0NzMxOTg0O0tldmluO2xrbXN3fDExMTExMDAxMTAxMDAwMTAwMTAxMHw1LjgxNzU0ODkxNDAxMzI2NGUrNDU7MS40ODcwMDk1NTEzMTg0NjMzZSs0NjsxODY4MjsyNDI4OzEuMDgyODY3ODY5OTM1ODUwOGUrNDY7NjE1Mzs1OzI0OzIuMDczMDc5MTkzMDEzNTAwN2UrNDY7MTswOzA7MDstMTs3OzE1MDsyLjU2OTEyNzg5MDA2MDk5OGUrNDQ7NTQ7MTQ7ODY7ODc1MzIyOzU7Y2hyaXN0bWFzOzEuNjEwMzIzNDc3MjM0ODY4OGUrNDU7MTI7Mjc0NzA4NDE1NzAxOzM2NTM4NDk1OTM5OzIzODE2OTkxOTc2MjswOzA7NDYyOzQ5NDs2NjE7NDQyOzYxMzsyNTsxNDsxODswOzU1OzA7MDsxOzE2NDsxNjI1NzUzOTU2NTgzOzA7MDsyMjcsMTI5LDQyNywzNDMsNDI0OzQxOzE7MTsxLjYyNDM1NTQ1NTUzNTIxMzVlKzQwO3w2ODMsMTAzMywzLjI1ODkzMDQzMzQzMzA2MzZlKzQzLDEwLCwwLDY4Mzs2NzksMTAyOSwyLjk2OTA0NjQ4MjExODg5OGUrNDMsMSwsMSw2Nzk7NjI5LDk3OSw1Ljc3NzcwNzcyMjMxNDc3M2UrMzksMTAsMTYyNTc1NDg5MTY1NDoxOjE2MjU3NDk5MjM0NTI6MDo1NTo1ODk6MTowOjE2MjU1OTkzMDcyMjU6IDExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMDAgOTo0NTo5OjQ4Ojk6NDI6ODozNjoxODozOjMwOjk3Ojk6NDM6MTg6NToxODo1Ojg6MzM6MTg6MzoxODoxOjk6NDQ6OTo0NTo5OjQ2Ojg6MzI6MzA6ODU6MzA6OTk6ODo1ODo4OjU4Ojg6NjY6MjU6Njk6MzA6ODM6MTg6NjozMDo4OToyMzo5OjMwOjk4OjA6MDowOjA6MzA6ODg6MjU6MjA6MzA6OTc6MzA6ODg6MzA6OTI6MzA6OTc6MzA6OTU6LDAsNjI5OzYxNCw5NjQsMy42NjkwNjIxNzM3Mzk5MTY1ZSs0MSwxLCwxLDYxNDs1OTQsOTQ0LDYuMDM2NDE5NDY0OTAyOTgxZSs0MCwxLCwxLDU5NDs1ODIsOTMyLDEuNDc3MTExMDIwODI5NjYyNGUrNDAsMSwwOjA6MTowOjA6IDk2Mjo0Oi00ODoxMTE6MDowOjAhNTYzNjoxOjY0OjMyMzowOjA6MCEyNDA3OjI6LTQ5OjI0OjA6MDowITY1NDY6MTo2NDo0NDc6MDowOjAhNTY2OTo1OjEzOjI1ODowOjA6MCEzOTU6NDotMTU1OjcyMjowOjA6MCExNzk1OjQ6LTE0Njo4NjowOjA6MCExMDAzMToxOjMwOjI2NzowOjA6MCExNDk5OjQ6LTE1NzoyMjA6MDowOjAhOTg1NTowOi00OjE0NDowOjA6MCE3OTA1OjI6LTU1OjQ1MDowOjA6MCExMDgzNTo1OjI6ODY1OjA6MDowITEzNTAyOjE6MTA6MzY5OjA6MDowITEwODY1OjI6LTYwOjM1NTowOjA6MCE0ODc4OjQ6LTE5Nzo0ODk6MDowOjAhMTMxMzY6MjotNDY6MTM2OjA6MDowISAwLDEsNTgyOzU2Miw5MTIsNS42MzI5OTg2MzI5MjA4MDhlKzQwLDEsMS8xMC82LzggMSAxNjI1NzQ4OTc3Njc3IDAsMSw1NjI7MTAzLDE0NzMsMi4wMDE1OTg3NTE4MjM4NjU0ZSs0MCwyLDQ3LjA3NDg0NTcyNTI1MzczIDE0IDM3NiAxLDAsNjAwOzUyMSw4NzEsNi4wMjg2NzE2NjE1Nzk1NzllKzM5LDEsLDEsNTIxOzUwMiw4NTIsMS43NDc4NzA3MjMyODQwMTI1ZSs0MCwxLCwxLDUwMjs0OTgsODQ4LDEuODg2NzU1NzE2NjM4NjI4ZSs0MiwxLCwxLDQ5ODs0NjMsODEzLDQuMDk0Njc4MTM3NDM4ODgwNmUrNDEsMiwsMSw0NjM7NDQ4LDc5OCwyLjgxODczNDk4NjkyMjAxN2UrNDIsMiwsMSw0NDg7NDQyLDc5MiwxLjUyNTY2NTYwMjE5MzQyNTRlKzQzLDIsLDEsNDQyOzQyNyw3NzcsMy4yODMyNTM4OTY4MTQyNjJlKzQzLDIsLDEsNDI3OzQyMyw3NzQsMS43ODIyNTk3MDYyODEyNjEyZSs0NCwzLCwxLDQyMzszNzIsNzIyLDMuNjgxNzk0NDcyNTQxOTc5ZSs0MywyLCwxLDM3MjszNDQsNjk4LDEuNDk0OTE5MDE2NzAwODYxNmUrNDQsNiwsMSwzNDU7fDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDExMTExMTExMDAxMTExMTEwMDAwMDAxMTAwMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTAxMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAxMTAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTAxMDEwMTAwMDAwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMDAwMDAwMDAwMDExMTExMTAwMDAwMDExMTEwMDExMTExMTExMDAxMTExMTExMTExMTExMTExMDAxMDEwMDAxMTExMTExMTExMTEwMDExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTAwMDAwMDExMTExMDAwMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMDExMDAxMTExMDAwMDAwMDAxMTExMTExMXwxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTEwMTAxMTExMDExMTExMTAwMDAwMDAwMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMDExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMDAwMDAwMDAwMDAxMTAwMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMDEwMDExMTEwMTEwMDEwMDAxMDExMTExMTExMTExMTEwMDExMTExMTExMTEwMTExMDEwMTEwMTExMTExMTExMDAxMTEwMTEwMDAwMDAwMTEwMDAwMDAxMDAwMDAwMDExMTExMTExMTExMDAwMDAwMDAwMDExMTExMTAwMDAwMDAwMDExMTExMTExMDAwMDAxMTEwMTExMTAwMDAwMDAwfDAsNTQ5MCwxODg5LDc7fENvb2tpZU1vbnN0ZXI6eyJmYXZvdXJpdGVTZXR0aW5ncyI6WyJQUE9ubHlDb25zaWRlckJ1eWFibGUiLCJQUEV4Y2x1ZGVUb3AiLCJQUFNlY29uZHNMb3dlckxpbWl0IiwiR0NTb3VuZCIsIlNlYVNvdW5kIiwiSGVhdmVubHlDaGlwc1RhcmdldCIsIk1pc3NpbmdVcGdyYWRlcyIsIlNvcnRVcGdyYWRlcyIsIlNvcnRCdWlsZGluZ3MiXSwic2V0dGluZ3MiOnsiQm90QmFyIjoxLCJUaW1lckJhciI6MSwiVGltZXJCYXJQb3MiOjAsIkJ1aWxkQ29sb3IiOjEsIkJ1bGtCdWlsZENvbG9yIjowLCJDb2xvclBQQnVsa01vZGUiOjEsIlVwQmFyQ29sb3IiOjEsIlVwZ3JhZGVCYXJGaXhlZFBvcyI6MCwiQ2FsY1dyaW5rIjowLCJDUFNNb2RlIjoxLCJBdmdDUFNIaXN0IjoxLCJBdmdDbGlja3NIaXN0Ijo0LCJUb29sV2FybkJvbiI6MCwiR0NOb3RpZmljYXRpb24iOjAsIkdDRmxhc2giOjEsIkdDU291bmQiOjAsIkdDVm9sdW1lIjoyNiwiR0NTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzY2LzY2NzE3XzkzMTY1NS1scS5tcDMiLCJGb3J0dW5lTm90aWZpY2F0aW9uIjoxLCJGb3J0dW5lRmxhc2giOjAsIkZvcnR1bmVTb3VuZCI6MSwiRm9ydHVuZVZvbHVtZSI6NzksIkZvcnR1bmVTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzE3NC8xNzQwMjdfMzI0MjQ5NC1scS5tcDMiLCJTZWFOb3RpZmljYXRpb24iOjAsIlNlYUZsYXNoIjowLCJTZWFTb3VuZCI6MCwiU2VhVm9sdW1lIjoxMDAsIlNlYVNvdW5kVVJMIjoiaHR0cHM6Ly93d3cuZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyMS8xMjEwOTlfMjE5MzI2Ni1scS5tcDMiLCJHYXJkRmxhc2giOjEsIkdhcmRTb3VuZCI6MCwiR2FyZFZvbHVtZSI6ODgsIkdhcmRTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9wZW9wbGUvaG9kb21vc3R2YXJ1amVtcml0YW0vc291bmRzLzE3MTI3OS9kb3dubG9hZC8xNzEyNzlfX2hvZG9tb3N0dmFydWplbXJpdGFtX19sb3BhdGUxMi0zLndhdiIsIk1hZ2ljTm90aWZpY2F0aW9uIjowLCJNYWdpY0ZsYXNoIjowLCJNYWdpY1NvdW5kIjowLCJNYWdpY1ZvbHVtZSI6MTAwLCJNYWdpY1NvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMjIxLzIyMTY4M18xMDE1MjQwLWxxLm1wMyIsIldyaW5rbGVyTm90aWZpY2F0aW9uIjowLCJXcmlua2xlckZsYXNoIjowLCJXcmlua2xlclNvdW5kIjowLCJXcmlua2xlclZvbHVtZSI6MTAwLCJXcmlua2xlclNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTI0LzEyNDE4Nl84MDQzLWxxLm1wMyIsIldyaW5rbGVyTWF4Tm90aWZpY2F0aW9uIjoxLCJXcmlua2xlck1heEZsYXNoIjowLCJXcmlua2xlck1heFNvdW5kIjowLCJXcmlua2xlck1heFZvbHVtZSI6MTAwLCJXcmlua2xlck1heFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTUyLzE1Mjc0M18xNTY2My1scS5tcDMiLCJUaXRsZSI6MiwiVG9vbHRpcEluZm8iOjEsIlRvb2x0aXBBbW9yIjowLCJUb29sV2Fybkx1Y2t5IjowLCJUb29sV2Fybkx1Y2t5RnJlbnp5IjowLCJUb29sV2FybkNvbmp1cmUiOjAsIlRvb2xXYXJuQ29uanVyZUZyZW56eSI6MCwiVG9vbFdhcm5FZGlmaWNlIjowLCJUb29sV2FyblBvcyI6MSwiVG9vbHRpcEdyaW0iOjEsIlRvb2xXcmluayI6MSwiVG9vbHRpcEx1bXAiOjEsIkRyYWdvbkF1cmFJbmZvIjoxLCJTdGF0cyI6MSwiTWlzc2luZ1VwZ3JhZGVzIjoxLCJVcFN0YXRzIjowLCJUaW1lRm9ybWF0IjowLCJEZXRhaWxlZFRpbWUiOjEsIkdyaW1vaXJlQmFyIjoxLCJTY2FsZSI6MiwiU2NhbGVEZWNpbWFscyI6MSwiU2NhbGVTZXBhcmF0b3IiOjAsIlNjYWxlQ3V0b2ZmIjoiOTk5OTk5IiwiU29ydEJ1aWxkaW5ncyI6MywiU29ydFVwZ3JhZGVzIjoxLCJHQ1RpbWVyIjoxLCJGYXZpY29uIjoxLCJXcmlua2xlckJ1dHRvbnMiOjEsIkhlYWRlciI6eyJCYXJzQ29sb3JzIjoxLCJDYWxjdWxhdGlvbiI6MCwiTm90aWZpY2F0aW9uIjoxLCJOb3RpZmljYXRpb25HQyI6MCwiTm90aWZpY2F0aW9uRkMiOjAsIk5vdGlmaWNhdGlvblNlYSI6MCwiTm90aWZpY2F0aW9uR2FyZCI6MSwiTm90aWZpY2F0aW9uTWFnaSI6MCwiTm90aWZpY2F0aW9uV3JpbmsiOjAsIk5vdGlmaWNhdGlvbldyaW5rTWF4IjowLCJUb29sdGlwIjowLCJTdGF0aXN0aWNzIjowLCJOb3RhdGlvbiI6MCwiTWlzY2VsbGFuZW91cyI6MCwiTHVja3kiOjEsIlNwZWxscyI6MCwiQ2hhaW4iOjAsIlByZXN0aWdlIjowLCJXcmluayI6MCwiU2VhIjowLCJNaXNjIjowLCJOb3RpZmljYXRpb25HZW5lcmFsIjowLCJHYXJkZW4iOjEsIkluZm9UYWIiOjEsIkZhdm91cml0ZSI6MSwiQ29sb3VycyI6MCwiQmFyc0Rpc3BsYXkiOjAsIkFjaGlldnMiOjF9LCJUaW1lckJhck92ZXJsYXkiOjIsIlBQRXhjbHVkZVRvcCI6MywiUFBTZWNvbmRzTG93ZXJMaW1pdCI6Ii4xIiwiUFBPbmx5Q29uc2lkZXJCdXlhYmxlIjoxLCJHZW5lcmFsU291bmQiOjAsIlRvb2x0aXBCdWlsZFVwZ3JhZGUiOjEsIlRvb2xXYXJuVXNlciI6IiIsIlRvb2x0aXBXcmluayI6MSwiVG9vbHRpcFBsb3RzIjoxLCJUb29sdGlwQXNjZW5kQnV0dG9uIjoxLCJIZWF2ZW5seUNoaXBzVGFyZ2V0IjoiNzc3Nzc3IiwiU2hvd01pc3NlZEdDIjowLCJCdWxrQnV5QmxvY2siOjEsIlBQRGlzcGxheVRpbWUiOjEsIlRvb2x0aXBQYW50aGVvbiI6MSwiSGlkZVNlY3Rpb25zQnV0dG9ucyI6MSwiUFBSaWdpZGVsTW9kZSI6MCwiQnVpbGRDb2xvdXIiOjEsIkNvbG91ckJsdWUiOiIjNGJiOGYwIiwiQ29sb3VyR3JlZW4iOiIjMDBmZjAwIiwiQ29sb3VyWWVsbG93IjoiI2ZmZmYwMCIsIkNvbG91ck9yYW5nZSI6IiNmZjdmMDAiLCJDb2xvdXJSZWQiOiIjZmYwMDAwIiwiQ29sb3VyUHVycGxlIjoiI2ZmMDBmZiIsIkNvbG91ckdyYXkiOiIjYjNiM2IzIiwiQ29sb3VyUGluayI6IiNmZjE0OTMiLCJDb2xvdXJCcm93biI6IiM4YjQ1MTMiLCJVcEJhckNvbG91ciI6MSwiQ29sb3VyR0NGbGFzaCI6IiNGRkVCNjciLCJDb2xvdXJGb3J0dW5lRmxhc2giOiIjRkYzNkVEIiwiQ29sb3VyU2VhRmxhc2giOiIjRkZBREZDIiwiQ29sb3VyR2FyZEZsYXNoIjoiIzdDRkY0QyIsIkNvbG91ck1hZ2ljRmxhc2giOiIjZmZmZmZmIiwiQ29sb3VyV3JpbmtsZXJGbGFzaCI6IiNmZmZmZmYiLCJDb2xvdXJXcmlua2xlck1heEZsYXNoIjoiI0ZGRkZGRiIsIkZhdm91cml0ZVNldHRpbmdzIjoyLCJNaXNzaW5nQWNoaWV2ZW1lbnRzIjoxLCJVcGdyYWRlc05ldmVyQ29sbGFwc2UiOjEsIkF1dG9zYXZlVGltZXJCYXIiOjF9LCJ2ZXJzaW9uIjoiMi4wMzEuOSJ9Ow%3D%3D%21END%21
**Browser**
Chrome Version 91.0.4472.124 (Official Build) (64-bit)

**Comment by DanielNoord** [comment]
This works as intended. Indeed, as you describe, you will need to ignore the 3 best options if you don't want to see wizards light up.

I don't really see a reason why you would not want to select "ignore best 3" instead of "ignore best 1" besides it being 2 extra clicks. Those 2 extra clicks do mean that the option does exactly what it says it does, which I'm not in favour of changing.
