### ISSUE TITLE
CookieMonsterData idea

### ISSUE THREAD

**Issue by GhostGlitch** [CookieMonsterTeam/CookieMonster#892]
It would be really nice if CookieMonsterData could provide something similar to Game.UpgradesByID or a list of just the upgrades shown available for purchase. In the script that I am making that makes use of "CMD" I went with a more hacky way of getting upgrade Colors because I didn't want to have to iterate over both the upgrades on screen and all of those that exist while trying to match them up. Maybe I will eventually, but it would be nice if I didn't have to on my end.

**Comment by DanielNoord** [comment]
Looking at the data present in `CookieMonsterData` it seems that all upgrades that are not visible have a pp of `null`. You could check for this and then only use upgrades that have a pp that is actually a value?
However, I do think I might change this in the future as it would be a good optimisation to remove the calculation for non-available upgrades.

Another option would be to use `Game.UpgradesInStore` and take those with a `.pool` that is not `"toggle"`.

I might consider adding this to CookieMonster, but as we currently don't need it ourselves it might not be a priority.

**Comment by GhostGlitch** [comment]
Yeah, I'll probably wind up just completely rewriting the way I buy upgrades. That bit has a lot of code from the original code mine is based on and I just kinda hacked it to mostly work for my purposes. Those are some good ideas on how to manage it, didn't even know about `Game.UpgradesInStore`. problem with that route is that I still would have to itterate through the whole list of `CookieMonsterData` to get pp. But yeah, just filtering out null results and then buying it through Game functions is a much better way than the mess of JQuery I have that I barely understand.

**Comment by DanielNoord** [comment]
I think if you use `Game.UpgradesInStore` you don't need to iterate as you can just do `CookieMonsterData.Upgrades[UpgradeName].colour` to find the colour. With that approach you only need to iterate with over `Game.UpgradesInStore` which is by default always less than the total amount of upgrades.

**Comment by GhostGlitch** [comment]
Oh crap that's right, I definitely overcomplicated things. Something to add to the list.

**Comment by DanielNoord** [comment]
With #898 `CookieMonsterData.Upgrades` now only shows upgrades currently available in store
