### ISSUE TITLE
Upgrade Bar not showing

### ISSUE THREAD

**Issue by TheMshary** [CookieMonsterTeam/CookieMonster#908]
**Describe the bug**
Please describe the bug and what you would have expected the mod to do
The Upgrade bar is just not showing up. I remember a long time ago (I recently got back to CC) it used to display a horizontal bar above the upgrades store that showed colored squares with numbers next to them. That doesn't appear anymore.

I went to Options > Infobars and Visual Settings > Upgrade colours with bar ON and set Upgrade bar with fixed position ON

I tried this on Microsoft Edge also, same issue.

**To Reproduce**
The steps needed to reproduce the behavior:
1. Use the save file added below
2. Load Cookie Monster
3. Set settings to display the upgrade bar
4. The upgrade bar does not appear

**Screenshots**
![Cookie Monster](https://user-images.githubusercontent.com/8212884/126869729-655cb4ec-b08c-4d54-9932-8d4a54405617.PNG)

**Save file**
```
Please add a save file here.
This makes debugging much easier as we do not always have a good test save to debug the issue
[ShinyKittenBakery.txt](https://github.com/CookieMonsterTeam/CookieMonster/files/6872464/ShinyKittenBakery.txt)
```
**Browser**
Please specify your current browser. This can help find/fix the bug!
Google Chrome Version 91.0.4472.164 (Official Build) (32-bit)
Also tried on Microsoft Edge Version 92.0.902.55 (Official build) (64-bit)

**Comment by DanielNoord** [comment]
Found a fix:
Add `ToggleUpgradeBarAndColor()` back to relevant setting.

Will fix for next version!

**Comment by TheMshary** [comment]
Thank you so much! The bar is back on now.
