### ISSUE TITLE
Magic Meter keeps showing current amount of magic as "NaN" instead of the actual amount.

### ISSUE THREAD

**Issue by Gathaeryx** [CookieMonsterTeam/CookieMonster#939]
As shown in the following picture:
![image](https://user-images.githubusercontent.com/63103581/129932908-200c1285-8120-465b-bc13-fae6f4ba95ae.png)

Happens in both Chrome and Firefox, including on a fresh new game.

**Comment by DanielNoord** [comment]
Please use the bug report form to file any bug reports, this helps me in troubleshooting the issue and saves us both time :)
Could you paste in your save-file? Without it I won't be able to pinpoint the issue!
