### ISSUE TITLE
Game freezes when buying upgrade with mod enabled

### ISSUE THREAD

**Issue by ZapTap** [CookieMonsterTeam/CookieMonster#946]
**Describe the bug**
Purchasing the "Train Breath of Milk" Krumblor upgrade causes the game to freeze.
Doing the same without the mod enabled does not cause any such issue.
Even purchasing the upgrade, saving, then reloading the mod causes the game to lock up.
Currently using CC 2.031 and CM 2.031.10

**To Reproduce**
The steps needed to reproduce the behavior:
1. Load game with Cookie Monster enabled
2. buy Krumblor upgrade "Train Breath of Milk"

**Screenshots**

**Save file**
[DiscoSpaghettiBakery (1).txt](https://github.com/CookieMonsterTeam/CookieMonster/files/7032409/DiscoSpaghettiBakery.1.txt)

**Browser**
Using Chrome 73.0.3683.86

**Comment by ZapTap** [comment]
Console output:
Dragon.js:22 Uncaught TypeError: e.replaceAll is not a function
    at Xn (Dragon.js:22)
    at HTMLDivElement.l.childNodes.className.l.children.onmouseover (Dragon.js:52)
Xn @ Dragon.js:22
l.childNodes.className.l.children.onmouseover @ Dragon.js:52
Dragon.js:22 Uncaught TypeError: e.replaceAll is not a function
    at Xn (Dragon.js:22)
    at Array.ua (LoopHook.js:53)
    at Object.Game.runModHook (main.js?v=2.090:1499)
    at Object.Game.Logic (main.js?v=2.090:14235)
    at Object.Game.Logic (ReplaceNative.js:134)
    at Game.Loop (main.js?v=2.090:14395)
Xn @ Dragon.js:22
ua @ LoopHook.js:53
Game.runModHook @ main.js?v=2.090:1499
Game.Logic @ main.js?v=2.090:14235
Game.Logic @ ReplaceNative.js:134
Game.Loop @ main.js?v=2.090:14395
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
setTimeout (async)
Game.Loop @ main.js?v=2.090:14458
Dragon.js:22 Uncaught TypeError: e.replaceAll is not a function
    at Xn (Dragon.js:22)
    at HTMLDivElement.l.childNodes.className.l.children.onmouseover (Dragon.js:52)

**Comment by DanielNoord** [comment]
This is due to your browser being a little outdated.
Is it possible for you to upgrade to the latest version of Chrome?

**Comment by ZapTap** [comment]
Sure enough, that did it - thank you!
